In [ ]:
#Importar bibliotecas
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [ ]:
df = pd.read_csv("accident.csv")
df

     age  gender  speed helmet seatbelt  survived
0     18  Female     20     No      Yes         1
1     28    Male     20    Yes       No         1
2     52    Male     20    Yes       No         1
3     52  Female     20     No       No         1
4     37  Female     21     No       No         1
..   ...     ...    ...    ...      ...       ...
195   50  Female    118    Yes      Yes         0
196   59  Female    118    Yes       No         0
197   67  Female    118    Yes       No         0
198   24  Female    119    Yes      Yes         0
199   62  Female    119    Yes      Yes         0

[200 rows x 6 columns]

PARSIMONIA

In [ ]:
df.gender = df.gender.map({"Male": 1, "Female":0 })
df.helmet = df.helmet.map({"Yes": 1, "No": 0})
df.seatbelt = df.seatbelt.map({"Yes": 1, "No": 0})

df

     age  gender  speed  helmet  seatbelt  survived
0     18       0     20       0         1         1
1     28       1     20       1         0         1
2     52       1     20       1         0         1
3     52       0     20       0         0         1
4     37       0     21       0         0         1
..   ...     ...    ...     ...       ...       ...
195   50       0    118       1         1         0
196   59       0    118       1         0         0
197   67       0    118       1         0         0
198   24       0    119       1         1         0
199   62       0    119       1         1         0

[200 rows x 6 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x = df.drop("survived", axis=1)
y = df.survived

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=31)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [ ]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

logit_model = smf.logit('survived ~ age + speed + helmet + seatbelt + gender', data=df)
result = logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.535814
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:               survived   No. Observations:                  200
Model:                          Logit   Df Residuals:                      194
Method:                           MLE   Df Model:                            5
Date:                Sat, 13 Sep 2025   Pseudo R-squ.:                  0.2202
Time:                        00:37:57   Log-Likelihood:                -107.16
converged:                       True   LL-Null:                       -137.42
Covariance Type:            nonrobust   LLR p-value:                 9.543e-12
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9079      0.733      3.967      0.000       1.471       4.345
age           -0.0310      0.012     -2.663      0.008      -0.054      -0.008
speed         -0.0380      0.006     -5.901      0.000      -0.051      -0.025
helmet         0.7669      0.346      2.214      0.027       0.088       1.446
seatbelt       0.3210      0.339      0.947      0.343      -0.343       0.985
gender         0.4141      0.335      1.236      0.216      -0.243       1.071
==============================================================================

- Edad -> Influye
- Velocidad -> Influye
- casco -> Influye
- Seguridad -> No inflye
- Género -> No influye

In [ ]:
#QUITAR SEATBEALT Y GENERO
import statsmodels.api as sm
import statsmodels.formula.api as smf

df_cleaned = df.dropna()

logit_model = smf.logit('survived ~ age + speed + helmet', data=df_cleaned)
result = logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.541662
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:               survived   No. Observations:                  200
Model:                          Logit   Df Residuals:                      196
Method:                           MLE   Df Model:                            3
Date:                Sat, 13 Sep 2025   Pseudo R-squ.:                  0.2117
Time:                        00:37:57   Log-Likelihood:                -108.33
converged:                       True   LL-Null:                       -137.42
Covariance Type:            nonrobust   LLR p-value:                 1.446e-12
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.2529      0.698      4.660      0.000       1.885       4.621
age           -0.0312      0.012     -2.708      0.007      -0.054      -0.009
speed         -0.0378      0.006     -5.917      0.000      -0.050      -0.025
helmet         0.8111      0.344      2.359      0.018       0.137       1.485
==============================================================================

In [ ]:
#Orden de importancia de las variables
# A mayor valor, más importancia
from sklearn.inspection import permutation_importance
import matplotlib.pyplot as plt

result=permutation_importance(model, x_train, y_train, n_repeats=10, random_state=42, n_jobs=-1)
print(result.importances_mean)

[0.085625 0.03     0.154375 0.049375 0.00875 ]

In [ ]:
#Dame el nombre de cada variable, ***para saber qué valor pertenece a qué
x_test.columns.to_list()

['age', 'gender', 'speed', 'helmet', 'seatbelt']

- ['age', 'gender', 'speed', 'helmet', 'seatbelt']
- [0.085625 0.03     0.154375 0.049375 0.00875 ]

In [ ]:
#Agrupar y ordenar
sorted(zip(result.importances_mean, x_test.columns.to_list()))

[(np.float64(0.008750000000000003), 'seatbelt'),
 (np.float64(0.030000000000000006), 'gender'),
 (np.float64(0.04937499999999999), 'helmet'),
 (np.float64(0.085625), 'age'),
 (np.float64(0.154375), 'speed')]