In [37]:
import pandas as pd
df = pd.read_csv('flight_price.csv')
df.head()

,id,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [39]:
X = df.drop(['id','flight','price'], axis=1)
y = df['price']

## Cuando una variables es categórica tengo 2 opciones
* ORDINAL
* NOMINAL
- Para la regresión lineal es mejor usar dummies
### DUMMIES
* Es una categoría menos (de 8 variables se conviertene en 7)
* Tomar una categoría de referencia (arbitrariamente)
*

In [40]:
X = pd.get_dummies(X, drop_first=True, dtype=int)  #drop_first -> el primero que sale es el que toma como referencia   || Aerolinea es la referencia en el ejemplo
X

,duration,days_left,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara,source_city_Chennai,source_city_Delhi,source_city_Hyderabad,...,arrival_time_Evening,arrival_time_Late_Night,arrival_time_Morning,arrival_time_Night,destination_city_Chennai,destination_city_Delhi,destination_city_Hyderabad,destination_city_Kolkata,destination_city_Mumbai,class_Economy
0,2.17,1,0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,1,1
1,2.33,1,0,0,0,1,0,0,1,0,...,0,0,1,0,0,0,0,0,1,1
2,2.17,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,1
3,2.25,1,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,1,1
4,2.33,1,0,0,0,0,1,0,1,0,...,0,0,1,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,10.08,49,0,0,0,0,1,1,0,0,...,1,0,0,0,0,0,1,0,0,0
300149,10.42,49,0,0,0,0,1,1,0,0,...,0,0,0,1,0,0,1,0,0,0
300150,13.83,49,0,0,0,0,1,1,0,0,...,0,0,0,1,0,0,1,0,0,0
300151,10.00,49,0,0,0,0,1,1,0,0,...,1,0,0,0,0,0,1,0,0,0
300152,10.08,49,0,0,0,0,1,1,0,0,...,1,0,0,0,0,0,1,0,0,0

In [41]:
import statsmodels.api as sm

X = sm.add_constant(X)
model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.911
Model:                            OLS   Adj. R-squared:                  0.911
Method:                 Least Squares   F-statistic:                 1.030e+05
Date:                Sat, 11 Oct 2025   Prob (F-statistic):               0.00
Time:                        03:14:52   Log-Likelihood:            -3.0726e+06
No. Observations:              300153   AIC:                         6.145e+06
Df Residuals:                  300122   BIC:                         6.146e+06
Df Model:                          30
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                         5.257e+04     94.286    557.511      0.000    5.24e+04    5.28e+04
duration                        42.5731      2.344     18.160      0.000      37.978      47.168
days_left                     -130.9517      0.912   -143.647      0.000    -132.738    -129.165
airline_Air_India              116.4140     62.962      1.849      0.064      -6.990     239.818
airline_GO_FIRST              1705.7026     70.217     24.292      0.000    1568.080    1843.325
airline_Indigo                2107.1783     64.313     32.764      0.000    1981.126    2233.230
airline_SpiceJet              2294.1916     91.066     25.193      0.000    2115.705    2472.678
airline_Vistara               4071.5088     60.978     66.770      0.000    3951.994    4191.024
source_city_Chennai            -67.4818     46.273     -1.458      0.145    -158.176      23.213
source_city_Delhi            -1405.9013     42.012    -33.465      0.000   -1488.243   -1323.560
source_city_Hyderabad        -1679.0324     45.914    -36.569      0.000   -1769.023   -1589.042
source_city_Kolkata           1583.7058     44.475     35.609      0.000    1496.537    1670.875
source_city_Mumbai            -211.8791     41.834     -5.065      0.000    -293.872    -129.886
departure_time_Early_Morning   835.6850     41.381     20.195      0.000     754.579     916.791
departure_time_Evening         733.8114     42.047     17.452      0.000     651.400     816.222
departure_time_Late_Night     1694.4629    191.676      8.840      0.000    1318.784    2070.142
departure_time_Morning         856.3184     40.468     21.160      0.000     777.002     935.635
departure_time_Night           690.1368     45.581     15.141      0.000     600.800     779.474
stops_two_or_more             2105.3377     62.003     33.955      0.000    1983.813    2226.862
stops_zero                   -7585.7538     45.922   -165.188      0.000   -7675.759   -7495.748
arrival_time_Early_Morning    -771.9774     66.252    -11.652      0.000    -901.829    -642.126
arrival_time_Evening           924.6971     42.840     21.585      0.000     840.731    1008.663
arrival_time_Late_Night        953.2546     69.734     13.670      0.000     816.579    1089.931
arrival_time_Morning           476.6186     45.039     10.582      0.000     388.343     564.895
arrival_time_Night            1142.6035     41.975     27.221      0.000    1060.334    1224.873
destination_city_Chennai      -219.8228     45.868     -4.793      0.000    -309.723    -129.923
destination_city_Delhi       -1553.8495     43.057    -36.089      0.000   -1638.239   -1469.460
destination_city_Hyderabad   -1720.0619     45.470    -37.828      0.000   -1809.182   -1630.942
destination_city_Kolkata      1376.7858     43.904     31.359      0.000    1290.735    1462.837
destination_city_Mumbai        -28.7668     42.359     -0.679      0.497    -111.789      54.255
class_Economy                -4.492e+04     30.107  -1492.108      0.000    -4.5e+04   -4.49e+04
==============================================================================
Omnibus:                    39556.303   Durbin-Watson:                   0.336
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           337099.325
Skew:                           0.357   Prob(JB):                         0.00
Kurtosis:                       8.143   Cond. No.                         490.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

ELIMINAR VARIABLES
* Más de 0.05 se elimina UNA POR UNA

INTERPRETAR COEFICIENTES
* airline_GO_FIRST CUESTA (CAMBIA) 1621.8750 MÁS QUE LA REFERENCIA
* Salir de source_city_Chennai  CUESTA -67.4818 (MENOS) QUE LA REFERENCIA
* La clase class_Economy CUESTA -4.492e+04  (MENOS) QUE LA REFERENCIA (BUSSINES)
* Cada hora que dure tu vuelo (duration) CUESTA  42.5731 MÁS

In [42]:
X = X.drop(['destination_city_Mumbai'], axis=1)
model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.911
Model:                            OLS   Adj. R-squared:                  0.911
Method:                 Least Squares   F-statistic:                 1.065e+05
Date:                Sat, 11 Oct 2025   Prob (F-statistic):               0.00
Time:                        03:14:53   Log-Likelihood:            -3.0726e+06
No. Observations:              300153   AIC:                         6.145e+06
Df Residuals:                  300123   BIC:                         6.146e+06
Df Model:                          29
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                         5.255e+04     90.343    581.641      0.000    5.24e+04    5.27e+04
duration                        42.6333      2.343     18.199      0.000      38.042      47.225
days_left                     -130.9489      0.912   -143.646      0.000    -132.736    -129.162
airline_Air_India              113.9035     62.853      1.812      0.070      -9.287     237.094
airline_GO_FIRST              1704.1618     70.180     24.283      0.000    1566.611    1841.712
airline_Indigo                2106.4863     64.305     32.758      0.000    1980.450    2232.522
airline_SpiceJet              2292.0584     91.012     25.184      0.000    2113.678    2470.438
airline_Vistara               4070.3046     60.952     66.779      0.000    3950.840    4189.769
source_city_Chennai            -64.9382     46.121     -1.408      0.159    -155.335      25.458
source_city_Delhi            -1402.2380     41.664    -33.656      0.000   -1483.898   -1320.578
source_city_Hyderabad        -1676.0601     45.705    -36.671      0.000   -1765.641   -1586.479
source_city_Kolkata           1586.8241     44.237     35.871      0.000    1500.121    1673.527
source_city_Mumbai            -205.1475     40.642     -5.048      0.000    -284.805    -125.490
departure_time_Early_Morning   834.9709     41.368     20.184      0.000     753.891     916.051
departure_time_Evening         733.3000     42.040     17.443      0.000     650.902     815.698
departure_time_Late_Night     1693.8810    191.674      8.837      0.000    1318.206    2069.556
departure_time_Morning         856.2585     40.468     21.159      0.000     776.943     935.574
departure_time_Night           689.5891     45.574     15.131      0.000     600.266     778.912
stops_two_or_more             2106.9656     61.957     34.007      0.000    1985.532    2228.399
stops_zero                   -7585.8607     45.922   -165.191      0.000   -7675.866   -7495.856
arrival_time_Early_Morning    -771.7665     66.251    -11.649      0.000    -901.617    -641.916
arrival_time_Evening           926.0637     42.793     21.640      0.000     842.190    1009.937
arrival_time_Late_Night        955.8003     69.633     13.726      0.000     819.322    1092.279
arrival_time_Morning           477.9364     44.998     10.621      0.000     389.743     566.130
arrival_time_Night            1142.9199     41.972     27.230      0.000    1060.656    1225.184
destination_city_Chennai      -205.0291     40.365     -5.079      0.000    -284.143    -125.915
destination_city_Delhi       -1538.4291     36.583    -42.054      0.000   -1610.130   -1466.728
destination_city_Hyderabad   -1704.8269     39.551    -43.105      0.000   -1782.345   -1627.308
destination_city_Kolkata      1391.7197     38.000     36.624      0.000    1317.240    1466.199
class_Economy                -4.492e+04     30.106  -1492.169      0.000    -4.5e+04   -4.49e+04
==============================================================================
Omnibus:                    39546.254   Durbin-Watson:                   0.336
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           337039.781
Skew:                           0.356   Prob(JB):                         0.00
Kurtosis:                       8.142   Cond. No.                         490.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

ELIMINAR UNA DUMMIE ES QUE NO HAY DIFERENCIA DE ESA VARIABLE CON LA DE REFERENCIA

In [43]:
X = X.drop(['source_city_Chennai'], axis=1)
model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.911
Model:                            OLS   Adj. R-squared:                  0.911
Method:                 Least Squares   F-statistic:                 1.103e+05
Date:                Sat, 11 Oct 2025   Prob (F-statistic):               0.00
Time:                        03:14:53   Log-Likelihood:            -3.0726e+06
No. Observations:              300153   AIC:                         6.145e+06
Df Residuals:                  300124   BIC:                         6.146e+06
Df Model:                          28
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                         5.252e+04     88.392    594.185      0.000    5.23e+04    5.27e+04
duration                        42.4829      2.340     18.154      0.000      37.896      47.070
days_left                     -130.9583      0.912   -143.660      0.000    -132.745    -129.172
airline_Air_India              111.4796     62.830      1.774      0.076     -11.665     234.624
airline_GO_FIRST              1705.2263     70.176     24.299      0.000    1567.683    1842.769
airline_Indigo                2101.7582     64.217     32.729      0.000    1975.894    2227.622
airline_SpiceJet              2288.5893     90.978     25.155      0.000    2110.274    2466.904
airline_Vistara               4067.9757     60.930     66.765      0.000    3948.555    4187.396
source_city_Delhi            -1375.1509     36.956    -37.210      0.000   -1447.584   -1302.717
source_city_Hyderabad        -1647.8802     41.090    -40.104      0.000   -1728.415   -1567.345
source_city_Kolkata           1614.9369     39.475     40.911      0.000    1537.568    1692.306
source_city_Mumbai            -178.2629     35.878     -4.969      0.000    -248.582    -107.944
departure_time_Early_Morning   836.7751     41.348     20.237      0.000     755.734     917.816
departure_time_Evening         737.9368     41.911     17.607      0.000     655.792     820.081
departure_time_Late_Night     1703.1246    191.561      8.891      0.000    1327.670    2078.580
departure_time_Morning         857.0063     40.464     21.179      0.000     777.697     936.316
departure_time_Night           688.8920     45.571     15.117      0.000     599.574     778.210
stops_two_or_more             2106.0516     61.953     33.994      0.000    1984.625    2227.479
stops_zero                   -7586.3966     45.920   -165.209      0.000   -7676.399   -7496.394
arrival_time_Early_Morning    -771.6380     66.251    -11.647      0.000    -901.488    -641.788
arrival_time_Evening           925.9273     42.793     21.637      0.000     842.054    1009.800
arrival_time_Late_Night        954.1452     69.623     13.704      0.000     817.686    1090.604
arrival_time_Morning           477.8585     44.998     10.620      0.000     389.665     566.052
arrival_time_Night            1142.0404     41.968     27.212      0.000    1059.785    1224.296
destination_city_Chennai      -198.0423     40.059     -4.944      0.000    -276.557    -119.528
destination_city_Delhi       -1536.2276     36.549    -42.032      0.000   -1607.863   -1464.592
destination_city_Hyderabad   -1701.8545     39.495    -43.091      0.000   -1779.263   -1624.446
destination_city_Kolkata      1394.4344     37.951     36.743      0.000    1320.051    1468.818
class_Economy                -4.492e+04     30.106  -1492.172      0.000    -4.5e+04   -4.49e+04
==============================================================================
Omnibus:                    39530.487   Durbin-Watson:                   0.336
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           336657.729
Skew:                           0.356   Prob(JB):                         0.00
Kurtosis:                       8.139   Cond. No.                         490.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [44]:
X = X.drop(['airline_Air_India'], axis=1)
model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.911
Model:                            OLS   Adj. R-squared:                  0.911
Method:                 Least Squares   F-statistic:                 1.144e+05
Date:                Sat, 11 Oct 2025   Prob (F-statistic):               0.00
Time:                        03:14:54   Log-Likelihood:            -3.0726e+06
No. Observations:              300153   AIC:                         6.145e+06
Df Residuals:                  300125   BIC:                         6.146e+06
Df Model:                          27
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                         5.261e+04     73.174    718.962      0.000    5.25e+04    5.28e+04
duration                        43.3984      2.283     19.013      0.000      38.925      47.872
days_left                     -130.9946      0.911   -143.735      0.000    -132.781    -129.208
airline_GO_FIRST              1621.8750     52.133     31.110      0.000    1519.695    1724.055
airline_Indigo                2019.1959     44.257     45.625      0.000    1932.454    2105.938
airline_SpiceJet              2199.7995     75.980     28.952      0.000    2050.881    2348.718
airline_Vistara               3973.4278     29.545    134.487      0.000    3915.520    4031.335
source_city_Delhi            -1376.2244     36.952    -37.244      0.000   -1448.649   -1303.800
source_city_Hyderabad        -1646.2921     41.080    -40.075      0.000   -1726.808   -1565.776
source_city_Kolkata           1613.6478     39.468     40.885      0.000    1536.292    1691.004
source_city_Mumbai            -175.5239     35.845     -4.897      0.000    -245.778    -105.270
departure_time_Early_Morning   837.9150     41.343     20.267      0.000     756.883     918.947
departure_time_Evening         738.2257     41.911     17.614      0.000     656.081     820.370
departure_time_Late_Night     1701.8107    191.561      8.884      0.000    1326.357    2077.264
departure_time_Morning         859.8602     40.433     21.266      0.000     780.613     939.107
departure_time_Night           687.2340     45.562     15.084      0.000     597.935     776.533
stops_two_or_more             2096.1795     61.703     33.972      0.000    1975.243    2217.116
stops_zero                   -7580.7251     45.809   -165.486      0.000   -7670.509   -7490.941
arrival_time_Early_Morning    -776.8876     66.185    -11.738      0.000    -906.609    -647.166
arrival_time_Evening           926.3294     42.793     21.647      0.000     842.457    1010.202
arrival_time_Late_Night        936.3177     68.894     13.591      0.000     801.287    1071.349
arrival_time_Morning           478.1834     44.997     10.627      0.000     389.990     566.377
arrival_time_Night            1143.3988     41.961     27.249      0.000    1061.157    1225.641
destination_city_Chennai      -197.8164     40.059     -4.938      0.000    -276.330    -119.302
destination_city_Delhi       -1537.9310     36.537    -42.093      0.000   -1609.542   -1466.320
destination_city_Hyderabad   -1701.6022     39.494    -43.085      0.000   -1779.010   -1624.194
destination_city_Kolkata      1392.0543     37.928     36.703      0.000    1317.717    1466.391
class_Economy                -4.493e+04     29.540  -1521.090      0.000    -4.5e+04   -4.49e+04
==============================================================================
Omnibus:                    39496.386   Durbin-Watson:                   0.336
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           335976.477
Skew:                           0.356   Prob(JB):                         0.00
Kurtosis:                       8.134   Cond. No.                         490.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [47]:
#CAMBIAR NOMBRE DE LA COLUMNA
df.rename(columns={'class': 'clase'}, inplace=True)

In [46]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
model = smf.ols('price ~ C(airline) + C(source_city) + C(departure_time) + C(stops) + C(arrival_time) + C(destination_city) + C(clase) + duration + days_left', data=df).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.911
Model:                            OLS   Adj. R-squared:                  0.911
Method:                 Least Squares   F-statistic:                 1.030e+05
Date:                Sat, 11 Oct 2025   Prob (F-statistic):               0.00
Time:                        03:14:59   Log-Likelihood:            -3.0726e+06
No. Observations:              300153   AIC:                         6.145e+06
Df Residuals:                  300122   BIC:                         6.146e+06
Df Model:                          30
Covariance Type:            nonrobust
======================================================================================================
                                         coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
Intercept                           5.257e+04     94.286    557.511      0.000    5.24e+04    5.28e+04
C(airline)[T.Air_India]              116.4140     62.962      1.849      0.064      -6.990     239.818
C(airline)[T.GO_FIRST]              1705.7026     70.217     24.292      0.000    1568.080    1843.325
C(airline)[T.Indigo]                2107.1783     64.313     32.764      0.000    1981.126    2233.230
C(airline)[T.SpiceJet]              2294.1916     91.066     25.193      0.000    2115.705    2472.678
C(airline)[T.Vistara]               4071.5088     60.978     66.770      0.000    3951.994    4191.024
C(source_city)[T.Chennai]            -67.4818     46.273     -1.458      0.145    -158.176      23.213
C(source_city)[T.Delhi]            -1405.9013     42.012    -33.465      0.000   -1488.243   -1323.560
C(source_city)[T.Hyderabad]        -1679.0324     45.914    -36.569      0.000   -1769.023   -1589.042
C(source_city)[T.Kolkata]           1583.7058     44.475     35.609      0.000    1496.537    1670.875
C(source_city)[T.Mumbai]            -211.8791     41.834     -5.065      0.000    -293.872    -129.886
C(departure_time)[T.Early_Morning]   835.6850     41.381     20.195      0.000     754.579     916.791
C(departure_time)[T.Evening]         733.8114     42.047     17.452      0.000     651.400     816.222
C(departure_time)[T.Late_Night]     1694.4629    191.676      8.840      0.000    1318.784    2070.142
C(departure_time)[T.Morning]         856.3184     40.468     21.160      0.000     777.002     935.635
C(departure_time)[T.Night]           690.1368     45.581     15.141      0.000     600.800     779.474
C(stops)[T.two_or_more]             2105.3377     62.003     33.955      0.000    1983.813    2226.862
C(stops)[T.zero]                   -7585.7538     45.922   -165.188      0.000   -7675.759   -7495.748
C(arrival_time)[T.Early_Morning]    -771.9774     66.252    -11.652      0.000    -901.829    -642.126
C(arrival_time)[T.Evening]           924.6971     42.840     21.585      0.000     840.731    1008.663
C(arrival_time)[T.Late_Night]        953.2546     69.734     13.670      0.000     816.579    1089.931
C(arrival_time)[T.Morning]           476.6186     45.039     10.582      0.000     388.343     564.895
C(arrival_time)[T.Night]            1142.6035     41.975     27.221      0.000    1060.334    1224.873
C(destination_city)[T.Chennai]      -219.8228     45.868     -4.793      0.000    -309.723    -129.923
C(destination_city)[T.Delhi]       -1553.8495     43.057    -36.089      0.000   -1638.239   -1469.460
C(destination_city)[T.Hyderabad]   -1720.0619     45.470    -37.828      0.000   -1809.182   -1630.942
C(destination_city)[T.Kolkata]      1376.7858     43.904     31.359      0.000    1290.735    1462.837
C(destination_city)[T.Mumbai]        -28.7668     42.359     -0.679      0.497    -111.789      54.255
C(clase)[T.Economy]                -4.492e+04     30.107  -1492.108      0.000    -4.5e+04   -4.49e+04
duration                              42.5731      2.344     18.160      0.000      37.978      47.168
days_left                           -130.9517      0.912   -143.647      0.000    -132.738    -129.165
==============================================================================
Omnibus:                    39556.303   Durbin-Watson:                   0.336
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           337099.325
Skew:                           0.357   Prob(JB):                         0.00
Kurtosis:                       8.143   Cond. No.                         490.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Si quieres eliminar variables es mejor el procedimiento anterior, no este último